### ISSUE TITLE
problem trying to install guidata

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guidata#1]
below the detail. First hints:
 - pypi whishes now it to be normalized `setuptools\dist.py:285: UserWarning: Normalizing '1.7.0beta2' to '1.7.0b2'`
 - then this probably sphinx/colorama bug under python3.4, maybe there is a fix somewhere ? (I think I have it also for spyder) ... it would be easier if you could publish a wheel.
`python setup.py sdist bdist_wheel  --universal`

````
Collecting guidata
  Downloading guidata-1.7.0beta2.zip (437kB)
    100% |################################| 438kB 305kB/s
Building wheels for collected packages: guidata
  Running setup.py bdist_wheel for guidata
  Complete output from command D:\WinPythonQt5\basedir34\build\winpython-3.4.3.a
md64\python-3.4.3.amd64\python.exe -c "import setuptools;__file__='C:\\Users\\fa
mille\\AppData\\Local\\Temp\\pip-build-ne6s4dt8\\guidata\\setup.py';exec(compile
(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d
 C:\Users\famille\AppData\Local\Temp\tmpxuk111v5pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\guidata
  copying guidata\config.py -> build\lib\guidata
  copying guidata\configtools.py -> build\lib\guidata
  copying guidata\disthelpers.py -> build\lib\guidata
  copying guidata\gettext_helpers.py -> build\lib\guidata
  copying guidata\guitest.py -> build\lib\guidata
  copying guidata\hdf5io.py -> build\lib\guidata
  copying guidata\py3compat.py -> build\lib\guidata
  copying guidata\qthelpers.py -> build\lib\guidata
  copying guidata\qtwidgets.py -> build\lib\guidata
  copying guidata\userconfig.py -> build\lib\guidata
  copying guidata\userconfigio.py -> build\lib\guidata
  copying guidata\utils.py -> build\lib\guidata
  copying guidata\__init__.py -> build\lib\guidata
  creating build\lib\guidata\dataset
  copying guidata\dataset\dataitems.py -> build\lib\guidata\dataset
  copying guidata\dataset\datatypes.py -> build\lib\guidata\dataset
  copying guidata\dataset\qtitemwidgets.py -> build\lib\guidata\dataset
  copying guidata\dataset\qtwidgets.py -> build\lib\guidata\dataset
  copying guidata\dataset\textedit.py -> build\lib\guidata\dataset
  copying guidata\dataset\__init__.py -> build\lib\guidata\dataset
  creating build\lib\guidata\qt
  copying guidata\qt\compat.py -> build\lib\guidata\qt
  copying guidata\qt\QtCore.py -> build\lib\guidata\qt
  copying guidata\qt\QtDesigner.py -> build\lib\guidata\qt
  copying guidata\qt\QtGui.py -> build\lib\guidata\qt
  copying guidata\qt\QtSvg.py -> build\lib\guidata\qt
  copying guidata\qt\QtWebKit.py -> build\lib\guidata\qt
  copying guidata\qt\__init__.py -> build\lib\guidata\qt
  creating build\lib\guidata\tests
  copying guidata\tests\activable_dataset.py -> build\lib\guidata\tests
  copying guidata\tests\activable_items.py -> build\lib\guidata\tests
  copying guidata\tests\all_features.py -> build\lib\guidata\tests
  copying guidata\tests\all_items.py -> build\lib\guidata\tests
  copying guidata\tests\bool_selector.py -> build\lib\guidata\tests
  copying guidata\tests\callbacks.py -> build\lib\guidata\tests
  copying guidata\tests\config.py -> build\lib\guidata\tests
  copying guidata\tests\data.py -> build\lib\guidata\tests
  copying guidata\tests\datasetgroup.py -> build\lib\guidata\tests
  copying guidata\tests\disthelpers.py -> build\lib\guidata\tests
  copying guidata\tests\editgroupbox.py -> build\lib\guidata\tests
  copying guidata\tests\hdf5.py -> build\lib\guidata\tests
  copying guidata\tests\inheritance.py -> build\lib\guidata\tests
  copying guidata\tests\rotatedlabel.py -> build\lib\guidata\tests
  copying guidata\tests\text.py -> build\lib\guidata\tests
  copying guidata\tests\translations.py -> build\lib\guidata\tests
  copying guidata\tests\__init__.py -> build\lib\guidata\tests
  creating build\lib\guidata\images
  copying guidata\images\apply.png -> build\lib\guidata\images
  copying guidata\images\arredit.png -> build\lib\guidata\images
  copying guidata\images\busy.png -> build\lib\guidata\images
  copying guidata\images\cell_edit.png -> build\lib\guidata\images
  copying guidata\images\copy.png -> build\lib\guidata\images
  copying guidata\images\delete.png -> build\lib\guidata\images
  copying guidata\images\dictedit.png -> build\lib\guidata\images
  copying guidata\images\edit.png -> build\lib\guidata\images
  copying guidata\images\exit.png -> build\lib\guidata\images
  copying guidata\images\expander_down.png -> build\lib\guidata\images
  copying guidata\images\expander_right.png -> build\lib\guidata\images
  copying guidata\images\file.png -> build\lib\guidata\images
  copying guidata\images\fileclose.png -> build\lib\guidata\images
  copying guidata\images\fileimport.png -> build\lib\guidata\images
  copying guidata\images\filenew.png -> build\lib\guidata\images
  copying guidata\images\fileopen.png -> build\lib\guidata\images
  copying guidata\images\filesave.png -> build\lib\guidata\images
  copying guidata\images\filesaveas.png -> build\lib\guidata\images
  copying guidata\images\guidata.svg -> build\lib\guidata\images
  copying guidata\images\max.png -> build\lib\guidata\images
  copying guidata\images\min.png -> build\lib\guidata\images
  copying guidata\images\none.png -> build\lib\guidata\images
  copying guidata\images\not_found.png -> build\lib\guidata\images
  copying guidata\images\python.png -> build\lib\guidata\images
  copying guidata\images\quickview.png -> build\lib\guidata\images
  copying guidata\images\save_all.png -> build\lib\guidata\images
  copying guidata\images\selection.png -> build\lib\guidata\images
  copying guidata\images\settings.png -> build\lib\guidata\images
  copying guidata\images\shape.png -> build\lib\guidata\images
  copying guidata\images\xmax.png -> build\lib\guidata\images
  copying guidata\images\xmin.png -> build\lib\guidata\images
  creating build\lib\guidata\images\editors
  copying guidata\images\editors\edit.png -> build\lib\guidata\images\editors
  copying guidata\images\editors\editcopy.png -> build\lib\guidata\images\editor
s
  copying guidata\images\editors\editdelete.png -> build\lib\guidata\images\edit
ors
  copying guidata\images\editors\editpaste.png -> build\lib\guidata\images\edito
rs
  copying guidata\images\editors\edit_add.png -> build\lib\guidata\images\editor
s
  copying guidata\images\editors\fileimport.png -> build\lib\guidata\images\edit
ors
  copying guidata\images\editors\filesave.png -> build\lib\guidata\images\editor
s
  copying guidata\images\editors\imshow.png -> build\lib\guidata\images\editors
  copying guidata\images\editors\insert.png -> build\lib\guidata\images\editors
  copying guidata\images\editors\plot.png -> build\lib\guidata\images\editors
  copying guidata\images\editors\rename.png -> build\lib\guidata\images\editors
  creating build\lib\guidata\images\filetypes
  copying guidata\images\filetypes\doc.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\gif.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\html.png -> build\lib\guidata\images\filetype
s
  copying guidata\images\filetypes\jpg.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\pdf.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\png.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\pps.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\ps.png -> build\lib\guidata\images\filetypes
  copying guidata\images\filetypes\tar.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\tgz.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\tif.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\txt.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\xls.png -> build\lib\guidata\images\filetypes

  copying guidata\images\filetypes\zip.png -> build\lib\guidata\images\filetypes

  creating build\lib\guidata\locale
  creating build\lib\guidata\locale\fr
  creating build\lib\guidata\locale\fr\LC_MESSAGES
  copying guidata\locale\fr\LC_MESSAGES\guidata.mo -> build\lib\guidata\locale\f
r\LC_MESSAGES
  running build_scripts
  creating build\scripts-3.4
  copying and adjusting guidata-tests -> build\scripts-3.4
  copying guidata-tests.bat -> build\scripts-3.4
  running build_doc
  creating C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata\build\
sphinx
  creating C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata\build\
sphinx\doctrees
  creating C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata\build\
sphinx\html
  D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\s
ite-packages\setuptools\dist.py:285: UserWarning: Normalizing '1.7.0beta2' to '1
.7.0b2'
    normalized_version,
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata\setup.p
y", line 107, in <module>
      cmdclass=cmdclass)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\site-packages\wheel\bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\command\build.py", line 126, in run
      self.run_command(cmd_name)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata\setup.p
y", line 77, in run
      sphinx.setup_command.BuildDoc.run(self)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\site-packages\sphinx\setup_command.py", line 141, in run
      if not color_terminal():
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\site-packages\sphinx\util\console.py", line 58, in color_terminal
      colorama.init()
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\site-packages\colorama\initialise.py", line 31, in init
      wrap_stream(orig_stdout, convert, strip, autoreset, wrap)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\site-packages\colorama\initialise.py", line 61, in wrap_stream
      convert=convert, strip=strip, autoreset=autoreset)
    File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd
64\lib\site-packages\colorama\ansitowin32.py", line 68, in __init__
      convert = on_windows and not wrapped.closed and not on_emulated_windows an
d is_a_tty(wrapped)
  ValueError: underlying buffer has been detached

  ----------------------------------------
  Failed building wheel for guidata
Failed to build guidata
Installing collected packages: guidata
  Running setup.py install for guidata
    Complete output from command D:\WinPythonQt5\basedir34\build\winpython-3.4.3
.amd64\python-3.4.3.amd64\python.exe -c "import setuptools, tokenize;__file__='C
:\\Users\\famille\\AppData\\Local\\Temp\\pip-build-ne6s4dt8\\guidata\\setup.py';
exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\
n'), __file__, 'exec'))" install --record C:\Users\famille\AppData\Local\Temp\pi
p-hn4_xidk-record\install-record.txt --single-version-externally-managed --compi
le:
    running install
    running build
    running build_py
    running build_scripts
    running build_doc
    D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib
\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '1.7.0beta2' to
'1.7.0b2'
      normalized_version,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata\setup
.py", line 107, in <module>
        cmdclass=cmdclass)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata\setup
.py", line 77, in run
        sphinx.setup_command.BuildDoc.run(self)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\site-packages\sphinx\setup_command.py", line 141, in run
        if not color_terminal():
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\site-packages\sphinx\util\console.py", line 58, in color_terminal
        colorama.init()
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\site-packages\colorama\initialise.py", line 31, in init
        wrap_stream(orig_stdout, convert, strip, autoreset, wrap)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\site-packages\colorama\initialise.py", line 61, in wrap_stream
        convert=convert, strip=strip, autoreset=autoreset)
      File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.a
md64\lib\site-packages\colorama\ansitowin32.py", line 68, in __init__
        convert = on_windows and not wrapped.closed and not on_emulated_windows
and is_a_tty(wrapped)
    ValueError: underlying buffer has been detached

    ----------------------------------------
Command "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd6
4\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\famille\\AppDa
ta\\Local\\Temp\\pip-build-ne6s4dt8\\guidata\\setup.py';exec(compile(getattr(tok
enize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"
 install --record C:\Users\famille\AppData\Local\Temp\pip-hn4_xidk-record\instal
l-record.txt --single-version-externally-managed --compile" failed with error co
de 1 in C:\Users\famille\AppData\Local\Temp\pip-build-ne6s4dt8\guidata

D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64>
````

**Comment by stonebig** [comment]
installing a wheel (pre-made per a Python2.7 environnement, would nicely improve things .

https://github.com/PierreRaybaut/guidata/pull/2

**Comment by PierreRaybaut** [comment]
I've just uploaded a wheel package on PyPI.
I'm closing this one hoping that it solved the issue.

**Comment by stonebig** [comment]
thanks !
