### ISSUE TITLE
guidata-tests-py3 does not seems to work

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guidata#25]
I would like your opinion is it a bug in guidata or in python3.4 ?

$ guidata-tests-py3
Traceback (most recent call last):
  File "/usr/bin/guidata-tests-py3", line 3, in <module>
    tests.run()
  File "/usr/lib/python3/dist-packages/guidata/tests/__init__.py", line 17, in run
    run_testlauncher(guidata)
  File "/usr/lib/python3/dist-packages/guidata/guitest.py", line 164, in run_testlauncher
    win = TestLauncherWindow(package)
  File "/usr/lib/python3/dist-packages/guidata/guitest.py", line 134, in __init__
    tests = get_tests(test_package)
  File "/usr/lib/python3/dist-packages/guidata/guitest.py", line 38, in get_tests
    _temp = __import__(test_package.__name__, fromlist=[module_name])
  File "/usr/lib/python3/dist-packages/guidata/tests/userconfig_app.py", line 26, in <module>
    uc.set_application('app','1.0.0')
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 151, in set_application
    if version != self.get_version(version):
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 188, in get_version
    return self.get(self.default_section_name, 'version', version)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 312, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 319, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'

**Comment by PierreRaybaut** [comment]
Just tested with Python 3.4.3 on Ubuntu 14.04 and it works:
```console
pierre@gigabyte:~/guidata-1.7.0$ guidata-tests-py3
Settings saved in:  /home/pierre/.config/.app.ini
pierre@gigabyte:~/guidata-1.7.0$ python3 --version
Python 3.4.3
```

**Comment by PierreRaybaut** [comment]
(with latest `guidata` revision but I haven't done anything that should be related to that bug)

**Comment by picca** [comment]
This is strang but I have

    picca@mordor:~/.config$ python3 --version
    Python 3.4.3+

And the problem is still present.
I just checked and python3.5 gives the same error...
Maybe this is a problem with the py3compat layer.

**Comment by picca** [comment]
signature for python2

    ConfigParser.ConfigParser.get(self, section, option, raw=False, vars=None)

signature for pyton3

     configparser.ConfigParser.get(self, section, option, *, raw=False, vars=None, fallback=<object object at 0xb733ee08>)

maybe the problem is with this *
