### ISSUE TITLE
disthelpers.py test has issues

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guidata#26]
````
(40, 40)
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:487: RuntimeWarning: overflow encountered in byte_sca
lars
  self.lut = (LUT_MAX/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:488: RuntimeWarning: overflow encountered in byte_sca
lars
  -LUT_MAX*self.min/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:487: RuntimeWarning: overflow encountered in short_sc
alars
  self.lut = (LUT_MAX/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:488: RuntimeWarning: overflow encountered in short_sc
alars
  -LUT_MAX*self.min/(self.max-self.min),
--------------------------------------------------------------------------------

Adding item #0... Done
Adding item #1... Done
Adding item #2... Done
Adding item #3... Done
Adding item #4... Done
Assemble test1: 1500.0 x 1000.0
saving...
Assemble test2: 375.0 x 250.0
````

**Comment by PierreRaybaut** [comment]
Could you please copy/paste the traceback associated to this issue? (this is the same as https://github.com/PierreRaybaut/guiqwt/issues/49)

**Comment by PierreRaybaut** [comment]
It works for me with Python 3.4 and Python 2.7.

**Comment by stonebig** [comment]
launching from spyder but i a separate proces I get a smaller log:
````
Settings saved in:  D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\settings\.app.ini
Traceback (most recent call last):
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\guidata\tests\disthelpers.py", line 23, in <module>
    script="editgroupbox.py", target_name="demo.exe")
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\guidata\disthelpers.py", line 380, in setup
    assert osp.isfile(script)
AssertionError
````

**Comment by stonebig** [comment]
an experience on 'cx_freeze' works, after i did put the r''

````
import sys
from cx_Freeze import setup, Executable

setup(
    name = "On Dijkstra's Algorithm",
    version = "3.1",
    description = "A Dijkstra's Algorithm help tool.",
    executables = [Executable(r"D:\WinPythonQt5\basedir34\buildQt5\winpython-3.4.3.amd64\python-3.4.3.amd64\Lib\site-packages\sqlite_bro\sqlite_bro.py", base = "Win32GUI")])
    
````

I may have to digg further

**Comment by stonebig** [comment]
ok now, it compiles, but I don't guess where it puts the result
