### ISSUE TITLE
Creating guidata executables using pyinstaller

### ISSUE THREAD

**Issue by pmav99** [PierreRaybaut/guidata#41]
This is probably related to #9 

What steps will reproduce the problem?

1. Create a simple script (e.g. example given at the top of page https://code.google.com/p/guidata/)
2. Freeze using pyinstaller on windows (tested with python 2.7): `pyinstaller -D example.py`

The executable gets built, but when attempted to run. It gives the following error

```
\\vboxsvr\user\Prog\win\dist\example\guidata\images
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import guidata
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guidata\__init__.py", line 541, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guidata\config.py", line 19, in <module>
  File "site-packages\guidata\configtools.py", line 109, in add_image_module_path
  File "site-packages\guidata\configtools.py", line 95, in add_image_path
WindowsError: [Error 3] The system cannot find the path specified: u'\\\\vboxsvr\\user\\Prog\\win\\dist\\example\\guidata\\images\\*.*'
Failed to execute script example
```
I circumvented this by adding the directory containing the guidata images directly into pyinstaller's  spec file:

``` diff
-              datas=[],
+              datas=[
+                (r'C:\Python27\lib\site-packages\guidata\images', 'guidata\images'),
+              ],
```

I guess that this could be solved in a more straightforward way by changing `config.get_module_data_path` or something similar. If i have the time I might have a look at this.

**Comment by PierreRaybaut** [comment]
Here is another example of spec files for an executable based on guidata:
https://github.com/CODRA-Ingenierie-Informatique/CodraFT/blob/master/CodraFT.spec

AFAIK, there is no other way than specifying the data folders to be packaged.
