### ISSUE TITLE
Exception with Qt4/5 collision on python 3.5

### ISSUE THREAD

**Issue by quazgar** [PierreRaybaut/guidata#43]
With python 3.5, the collision between PyQt 4 and 5 is not caught upon import:

    try:
        from PyQt4.QtCore import PYQT_VERSION_STR as __version__ # analysis:ignore
    except ImportError:

This leads to the following exception backtrace:

    Traceback (most recent call last):
      ...
        import guidata.dataset.datatypes as dt
      File "/home/q/.local/lib/python3.5/site-packages/guidata/__init__.py", line 541, in <module>
        import guidata.config
      File "/home/q/.local/lib/python3.5/site-packages/guidata/config.py", line 15, in <module>
        from guidata.configtools import add_image_module_path, get_translation
      File "/home/q/.local/lib/python3.5/site-packages/guidata/configtools.py", line 22, in <module>
        from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
      File "/home/q/.local/lib/python3.5/site-packages/guidata/qt/__init__.py", line 54, in <module>
        from PyQt4.QtCore import PYQT_VERSION_STR as __version__ # analysis:ignore
    RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

It seems that python 3.6 turns PyQt's `RuntimeError` into an
`ImportError`, but on 3.5 the exception handling still fails.  A
simple fix would be to catch RuntimeErrors as well:

    except (ImportError, RuntimeError):

**Comment by PierreRaybaut** [comment]
Since v1.8, guidata relies on QtPy for Qt4/5 compatibility.
