### ISSUE TITLE
guidata doesn not work with the new spyder 2.3.6

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guidata#6]
picca@mordor:~/Debian/guidata/guidata$ guidata-tests
Traceback (most recent call last):
  File "/usr/bin/guidata-tests", line 3, in <module>
    tests.run()
  File "/usr/lib/python2.7/dist-packages/guidata/tests/__init__.py", line 16, in run
    from guidata.guitest import run_testlauncher
  File "/usr/lib/python2.7/dist-packages/guidata/guitest.py", line 17, in <module>
    from spyderlib.widgets.sourcecode.codeeditor import CodeEditor
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 25, in <module>
    from spyderlib.qt import is_pyqt46
  File "/usr/lib/python2.7/dist-packages/spyderlib/qt/__init__.py", line 23, in <module>
    sip.setapi('QDate', 2)
ValueError: API 'QDate' has already been set to version 1

ir seems to me that the fix done for python-qwt should be used also for guidata

**Comment by picca** [comment]
I can confirm that the fix work :)

**Comment by PierreRaybaut** [comment]
See commit 74a09d128e0a94113c218b971fc5436e4285caab.
