### ISSUE TITLE
setup error guiqwt under PyQt5 environnement

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guidata#8]
the setup of guiwqt rely on guidata module which seems to rely on Pyqt4 !? (I didn't get the error before, because setting 'QT-API' variable by hand to 'pyqt5' in previous method)

I don't know if you consider this a bug

````
Collecting guiqwt (from -r D:\WinPythonQt5\basedir34\requirements3.txt (line 2))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\famille\AppData\Local\Temp\pip-build-cx76pcw4\guiqwt\setup.py", line 28, in <module>
        from guidata.utils import get_subpackages, get_package_data, cythonize_all
      File "D:\WinpythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\guidata\__init__.py", line 538, in <module>
        import guidata.config
      File "D:\WinpythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\guidata\config.py", line 15, in <module>
        from guidata.configtools import add_image_module_path, get_translation
      File "D:\WinpythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\guidata\configtools.py", line 22, in <module>
        from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
      File "D:\WinpythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\guidata\qt\__init__.py", line 56, in <module>
        from PyQt4 import uic  # analysis:ignore
    ImportError: No module named 'PyQt4'
````

**Comment by stonebig** [comment]
thinking further, it's more my problem then guidata's
